let info = document.getElementById("info");
let cinema = document.getElementById("cinema");
let meetic = document.getElementById("meetic");
let framework = document.getElementById("framework");
let puissance = document.getElementById("puissance");
let twitter = document.getElementById("twitter");
let spotify = document.getElementById("spotify");

cinema.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "My cinema";
    let image = document.createElement("img");
    image.src = "./Image/cinema.png";
    image.alt = "cinema";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais faire un site de cinéma où l'on pouvait rechercher un film par nom/catégories, de pouvoir voir la liste des membres et de leurs grades. Ainsi que de pouvoir modifier ces derniers, de plus, on devait pouvoir ajouter une séance.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "Langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let php = document.createElement("li");
    let html = document.createElement("li");
    let css = document.createElement("li");
    let javascript = document.createElement("li");
    let sql = document.createElement("li");
    let phpLogo = document.createElement("img");
    phpLogo.src = "./Image/php.svg";
    phpLogo.alt = "logo php";
    php.appendChild(phpLogo);
    let htmlLogo = document.createElement("img");
    htmlLogo.src = "./Image/html.svg";
    html.alt = "logo html";
    html.appendChild(htmlLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    let javascriptLogo = document.createElement("img");
    javascriptLogo.src = "./Image/javascript.svg";
    javascriptLogo.alt = "logo javascript";
    javascript.appendChild(javascriptLogo);
    let sqlLogo = document.createElement("img");
    sqlLogo.src = "./Image/sql.svg";
    sqlLogo.alt = "logo sql";
    sql.appendChild(sqlLogo);
    liste.append(php, html, css, javascript, sql);
    divInfo.appendChild(liste);
});

meetic.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "My meetic";
    let image = document.createElement("img");
    image.src = "./Image/meetic.png";
    image.alt = "meetic";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais faire un site ayant les fonctionnalités de meetic ayant pour contrainte de vérifier si l'utilisateur est majeur ou non. Si l'utilisateur est mineur, il ne peut pas créer de compte et accéder aux fonctionnalités qui sont la recherche par genre, par tranche d'âge et par localisation. Je devais également faire un système de connexion avec les informations de l'utilisateur.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "Langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let php = document.createElement("li");
    let html = document.createElement("li");
    let css = document.createElement("li");
    let sql = document.createElement("li");
    let phpLogo = document.createElement("img");
    phpLogo.src = "./Image/php.svg";
    phpLogo.alt = "logo php";
    php.appendChild(phpLogo);
    let htmlLogo = document.createElement("img");
    htmlLogo.src = "./Image/html.svg";
    html.alt = "logo html";
    html.appendChild(htmlLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    let sqlLogo = document.createElement("img");
    sqlLogo.src = "./Image/sql.svg";
    sqlLogo.alt = "logo sql";
    sql.appendChild(sqlLogo);
    liste.append(php, html, css, sql);
    divInfo.appendChild(liste);
});

framework.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "Framework CSS";
    let image = document.createElement("img");
    image.src = "./Image/framework.png";
    image.alt = "framework";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais reproduire certaines fonctionnalités de bootstrap que ce soit la barre de navigation, le système de grille ou les boutons.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let html = document.createElement("li");
    let css = document.createElement("li");
    let scss = document.createElement("li");
    let htmlLogo = document.createElement("img");
    htmlLogo.src = "./Image/html.svg";
    html.alt = "logo html";
    html.appendChild(htmlLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    let scssLogo = document.createElement("img")
    scssLogo.src = "./Image/scss.svg";
    scssLogo.alt = "logo scss";
    scss.appendChild(scssLogo);
    liste.append(html, css, scss);
    divInfo.appendChild(liste);
});

puissance.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "Puissance 4";
    let image = document.createElement("img");
    image.src = "./Image/puissance4.png";
    image.alt = "puissance 4";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais refaire un jeu de société iconique qui est le puissance 4. Je devais le faire en module. L'objectif de ce jeu est très simple, le premier joueur qui aligne horizontalement ou verticalement ou en diagonnales 4 pions de la même couleur remporte la partie.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let html = document.createElement("li");
    let css = document.createElement("li");
    let javascript = document.createElement("li");
    let htmlLogo = document.createElement("img");
    htmlLogo.src = "./Image/html.svg";
    html.alt = "logo html";
    html.appendChild(htmlLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    let javascriptLogo = document.createElement("img");
    javascriptLogo.src = "./Image/javascript.svg";
    javascriptLogo.alt = "logo javascript";
    javascript.appendChild(javascriptLogo);
    liste.append(html, css, javascript);
    divInfo.appendChild(liste);
});

twitter.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "Twitter";
    let image = document.createElement("img");
    image.src = "./Image/twitter.png";
    image.alt = "twitter";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais refaire twitter et ses fonctionnalités que se soit de pouvoir se connecter, tweeter, retweeter, répondre au tweet et au messages, liker un tweet, un tweet avec 140 caractères maximum, pouvoir voir ses abonnés et ses abonnement et rechercher par tags de l'utilisateur.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let php = document.createElement("li");
    let html = document.createElement("li");
    let css = document.createElement("li");
    let javascript = document.createElement("li");
    let sql = document.createElement("li");
    let phpLogo = document.createElement("img");
    phpLogo.src = "./Image/php.svg";
    phpLogo.alt = "logo php";
    php.appendChild(phpLogo);
    let htmlLogo = document.createElement("img");
    htmlLogo.src = "./Image/html.svg";
    html.alt = "logo html";
    html.appendChild(htmlLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    let javascriptLogo = document.createElement("img");
    javascriptLogo.src = "./Image/javascript.svg";
    javascriptLogo.alt = "logo javascript";
    javascript.appendChild(javascriptLogo);
    let sqlLogo = document.createElement("img");
    sqlLogo.src = "./Image/sql.svg";
    sqlLogo.alt = "logo sql";
    sql.appendChild(sqlLogo);
    liste.append(php, html, css, javascript, sql);
    divInfo.appendChild(liste);
});

spotify.addEventListener("click", () =>
{
    info.innerHTML = "";
    let div = document.createElement("div");
    div.classList.add("text-center");
    info.appendChild(div);
    let title = document.createElement("h4");
    title.textContent = "Spotify";
    let image = document.createElement("img");
    image.src = "./Image/spotify.png";
    image.alt = "spotify";
    image.classList.add("w-50");
    image.classList.add("h-auto");
    div.appendChild(title);
    div.appendChild(image);
    let divInfo = document.createElement("div");
    divInfo.classList.add("w-50");
    divInfo.classList.add("margin-left-25");
    div.appendChild(divInfo);
    let detail = document.createElement("p");
    detail.textContent = "Durant ce projet, je devais reproduire certaines fonctionnalités de spotify qui sont la recherche, les albums et leurs détails, les genres et leurs détails et les artistes et leurs détails.";
    detail.classList.add("mt-3");
    detail.classList.add("start");
    divInfo.appendChild(detail);
    let language = document.createElement("h5");
    language.textContent = "langages utilisés:";
    divInfo.appendChild(language);
    let liste = document.createElement("ul");
    liste.classList.add("d-flex");
    liste.classList.add("evenly");
    let react = document.createElement("li");
    let docker = document.createElement("li");
    let css = document.createElement("li");
    let reactLogo = document.createElement("img");
    reactLogo.src = "./Image/react.svg";
    reactLogo.alt = "logo react";
    react.appendChild(reactLogo);
    let dockerLogo = document.createElement("img");
    dockerLogo.src = "./Image/docker.svg";
    dockerLogo.alt = "logo docker";
    docker.appendChild(dockerLogo);
    let cssLogo = document.createElement("img");
    cssLogo.src = "./Image/css.svg";
    cssLogo.alt = "logo css";
    css.appendChild(cssLogo);
    liste.append(react, docker, css);
    divInfo.appendChild(liste);
});